---

services:

  # front_next:
  #   container_name: next-app
  #   build: 
  #     context: ./frontend  #ルートディレクトリ
  #     dockerfile: ./dev.dockerfile
  #     target: dev
  #   tty: true
  #   ports:
  #     - ${NEXT_PORT}:3000
  #   env_file:
  #     - ./frontend/.next_env
  #   volumes:
  #     - ./frontend/next-app:/app
  #     - node_modules:/app/node_modules

  back_go:
    container_name: go-api
    build:
      context: ./backend
      dockerfile: ./dev.dockerfile
      target: dev
    tty: true
    ports:
      - ${GO_PORT}:8080
    env_file:
      - ./backend/.go_env
    volumes:
      - ./backend/src:/go/src/go_api
    networks:
      - yokoso

  db:
    container_name: yokoso_mysql
    build:
      context: ./db
      dockerfile: ./dev.dockerfile
    platform: linux/amd64
    ports:
      - 13306:3306
    tty: true
    restart: always
    networks:
      - yokoso

volumes:
  node_modules:
  db_data:

networks:
  yokoso: